# Generated by Django 3.0 on 2019-12-07 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sightings',
            name='id',
        ),
        migrations.AlterField(
            model_name='sightings',
            name='unique_squirrel_id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
