# Generated by Django 3.0 on 2019-12-08 22:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sightings', '0002_auto_20191207_1809'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sightings',
            name='age',
            field=models.CharField(choices=[('Adult', 'Adult'), ('Juvenile', 'Juvenile')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='latitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='location',
            field=models.CharField(choices=[('Ground Plane', 'Ground Plane'), ('Above Ground', 'Above Ground')], default='', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='longitude',
            field=models.FloatField(null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='other_activities',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='primary_fur_color',
            field=models.CharField(choices=[('Gray', 'Gray'), ('Black', 'Black'), ('Cinnamon', 'Cinnamon')], default='', max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='shift',
            field=models.CharField(choices=[('AM', 'AM'), ('PM', 'PM')], default='AM', max_length=3, null=True),
        ),
        migrations.AlterField(
            model_name='sightings',
            name='specific_location',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
